### PR TITLE
Add resources dirctory containing glow_logo.jpg

### PR DESCRIPTION
**Pull request by zbraiterman**
I have added a directory, called "resources", for images and have added a Glow logo to that directory.

### CODE REVIEW

**Review by plotnick — CHANGES_REQUESTED** [review]
I'd rather these diagrams go in a directory like `dapps/images`, since they're related to those dapps. They _definitely_ should not be in the top-level directory. There's also a spurious `glow` executable (?).

**Comment by zbraiterman** [comment]
> I'd rather these diagrams go in a directory like `dapps/images`, since they're related to those dapps. They _definitely_ should not be in the top-level directory. There's also a spurious `glow` executable (?).

Thanks. I’ll modify the directory, accordingly and will remove the spurious `glow` executable. 

Also, to confirm, do the diagrams look good to you, or do you think any of them should be modified/updated?

**Comment by zbraiterman** [comment]
I've just submitted pull request #414 to apply the changes @plotnick has requested.

**Comment by fare** [comment]
I still don't understand why these images are going here rather than in the mooc or glow-lang.org... We should probably reorganize these repositories a lot.

**Pull request closed without merging**
